[package]
name = "rusthanzuon-at-rust-ca-1-day-youth-boot-camp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
